### ISSUE TITLE
Outdated demo on website

### ISSUE THREAD

**Issue by cdkrot** [boazsegev/facil.io#13]
Just wanted to tell you, that you have a bug in demo on your website.

It is under "Simple API (Echo example)" section on "Getting started" page.

This is the compilation log:

> a.c: In function ‘create_echo_protocol’:
> a.c:45:19: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
>        .on_close = destroy_echo_protocol,
>                    ^~~~~~~~~~~~~~~~~~~~~
> a.c:45:19: note: (near initialization for ‘(anonymous).on_close’)
> 

And it really crashes when one tries to close connection to the server.

**Comment by boazsegev** [comment]
@cdkrot ,

Thank you so much! 🙏🏻

I guess that's what happens when development outpaces documentation. 😂

I assume you tested this with the stable branch.

I'll fix it soon ☺️👍🏻
