### ISSUE TITLE
Do you need a main() function if you are just building the shared object library?

### ISSUE THREAD

**Issue by tachang** [boazsegev/facil.io#135]
In buildroot I am doing the following:

```
FACIL_VERSION = ac0138add32474854833f762efe0e29cfe9995a6
FACIL_SITE = https://github.com/boazsegev/facil.io
FACIL_SITE_METHOD = git
FACIL_DEPENDENCIES =
FACIL_CONF_OPTS += --enable-shared
FACIL_INSTALL_STAGING = YES

$(eval $(cmake-package))
```

And result is:

```
* Disabled `-fipa-icf` optimization, might be buggy with this gcc version.
* Detected `epoll`
* Detected `sendfile` (Linux)
* Detected 'tm_zone' field in 'struct tm'
* Detected native socket API, without additional libraries
* No compatible SSL/TLS library detected.
* Detected Little Endian byte order.
* Linking...
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
makefile:659: recipe for target 'build' failed
make[1]: *** [build] Error 1
```

This makes sense. I don't have a main() function. However I would think the parameters I've added would create the shared object library only. Do you need some sort of main stub when making shared object libraries?

**Comment by boazsegev** [comment]
Hi @tachang ,

Thank you for opening this issue.

The facil.io library is not a shared library, it is a source code library. It requires no installation and it is used by adding the source code to whatever project you need it for.

This allows you to have multiple versions of facil.io running on the same system and using a new version does not break previously compiled programs (it also makes my docker images easier to build).

The experimental CMake support behaves the same way (adds the source files to your project).

However, you could make a static or dynamic library using `make lib`. I personally did not try doing it as that's not constructive for my use cases.

Good Luck.
