### ISSUE TITLE
Facil and linux epoll

### ISSUE THREAD

**Issue by f4r4** [boazsegev/facil.io#143]
Hey guys I am assuming facil uses epoll/poll.h on linux 
is there anyway to disable this and add facil as a library ?

**Comment by boazsegev** [comment]
Hi @f4r4 ,

You can look into [possible compilation macros](http://facil.io/0.7.x/fio#fio_engine_poll-fio_engine_epoll-fio_engine_kqueue) that will allow you to choose your own polling engine.

However, I'm not sure what it is you want to disable...?

If you want to use facil.io for its type system, without using a server at all, you can look into the facil.io CSTL library, which is still in development and designed to become the basis for the 0.8.x version (it is an amalgamation header library allowing you to selectively include whichever features you need, either as static functions or as externes functions).

**Comment by boazsegev** [comment]
Oh, I forgot to post the link to [the facil.io C STL repo](https://github.com/facil-io/cstl): https://github.com/facil-io/cstl

Just copy the header file (`fio-stl.h`) to your project. The [documentation](https://github.com/facil-io/cstl/blob/master/fio-stl.md) might be hard to read without styling, but you can either move through sections using the table of contents or use the [source documentation slices in the pre-merged folder](https://github.com/facil-io/cstl/tree/master/stl_slices).

Good luck!
