### ISSUE TITLE
Websocket: heavy `on_open` could cause a clienfirst message 

### ISSUE THREAD

**Issue by boazsegev** [boazsegev/facil.io#16]
As discovered by @madsheep and @nilclass, detailed in issue iodine#10 [here](https://github.com/boazsegev/iodine/issues/21#issuecomment-316724688), a client's first message might be lost due to a long `on_open`.

The issue seems to have been caused by the previous locking scheme, probably by the HTTP layer collecting the data instead of the Websocket.

At this point, the root of the cause is only guesswork. The issue prompted me to fragment the upgrade process (so now the `on_open` action is deferred), something that was on my internal TODO list for a while.

Along the way, the issue disappeared. I wish I know what was wrong with the previous upgrade locking scheme, so I would be sure the issue is solved and not masked... but it is what it is.

Credit to @madsheep and @nilclass, who did amazing work exposing the issue and tracking it down to the `on_open` callback.

**Comment by boazsegev** [comment]
I tracked down the root of the cause to the HTTP/1.x loop.

Now the loop is avoided, so new incoming data is handled in a separate event. Thus, if a protocol change (`upgrade`) occurred, the new protocol is invoked.

The issue in now grokked and resolved.

**Comment by madsheep** [comment]
👍 🥇
