### ISSUE TITLE
bad output in sha1

### ISSUE THREAD

**Issue by raminfp** [boazsegev/facil.io#19]
Hi @boazsegev ,

#18 i use example of README and compiled but i get bad output of program:

```bash
[root@raminfp ramin]# make
gcc -Iinclude  src/sha1.c src/sha2.c src/hex.c src/jalali.c src/misc.c src/random.c src/siphash.c src/main.c -o main
[root@raminfp ramin]# 
[root@raminfp ramin]# ./main 
sha1 : /���z-(�턞��v�9��

```

**Comment by boazsegev** [comment]
Hi @raminfp ,

Thanks for opening the issue and the related PR.

However, I'm not sure about what error you're experiencing. What output did you expect?

The [SHA1 algorithm results in 160 bits (or 20 bytes) of digest](https://en.wikipedia.org/wiki/SHA-1). It's not supposed to be a printable string.

If you want to encode the data in [Base64](https://github.com/boazsegev/facil.io/blob/master/lib/facil/bscrypt/bscrypt/base64.h), or maybe [using a Hex string](https://github.com/boazsegev/facil.io/blob/master/lib/facil/bscrypt/bscrypt/hex.h), you might find the data more human-friendly (though Hex takes double the space and Base64 takes about 4/3 of the space).

Or, is the output not the correct SHA1?

**Comment by raminfp** [comment]
Thanks for answer!

i haven't any error,but i use printf() for show`result` and i see `sha1 : /���z-(�턞��v�9����`

**Comment by raminfp** [comment]
@boazsegev can you explain with example code how to use [Base64](https://github.com/boazsegev/facil.io/blob/master/lib/facil/bscrypt/bscrypt/base64.h)  ?

**Comment by boazsegev** [comment]
I understand.

The SHA1 "string" value for "The quick brown fox jumps over the lazy dog" should be:

```c
const char expected[] = {0x2f, 0xd4, 0xe1, 0xc6, 0x7a, 0x2d, 0x28, 0xfc, 0xed, 0x84, 0x9e,
        0xe1, 0xbb, 0x76, 0xe7, 0x39, 0x1b, 0x93, 0xeb, 0x12, 0};
```

As you can see, some of the byte values aren't printable.

To convert to Base64 you will need at least 28 bytes (20/3*4 + NUL).

It would be something like (I'm typing this in Github, so I'm not testing the example code and I hope the autocorrect doesn't ruin my code):

```c
char buffer[28];

size_t len = bscrypt_base64_encode(buffer, sha1.digest.str, 20);
buffer[len] = 0;
// printf("Base64: %s", buffer);
```

**Comment by boazsegev** [comment]
P.S.

The `web socket_upgrade` function uses this exact sequence for computing an SHA1 hash and encoding it. [You can see the code here](https://github.com/boazsegev/facil.io/blob/18190689b423ba547e20e1f9b9cc705d85e7ee52/lib/facil/http/websockets.c#L933-L950).

**Comment by boazsegev** [comment]
I'm closing the issue because I don't think I need to fix something. But if you have more questions, please feel free to ask ☺️👍🏻

**Comment by raminfp** [comment]
Thanks again, still i have problem,

this is `return` int,
```int len = bscrypt_base64_encode(websockets_key, bscrypt_sha1_result(&sha1), 20);
```

still i am unable to see sha1 in this case, i see Base64 but how to convert binary sha1 in my output?

**Comment by raminfp** [comment]
it's OK Thanks @boazsegev

**Comment by boazsegev** [comment]
The return value is the string length. The Base64 string is stored in the `target` buffer.

In my example, the target was `char buffer[28];` and [in the Websocket code](https://github.com/boazsegev/facil.io/blob/18190689b423ba547e20e1f9b9cc705d85e7ee52/lib/facil/http/websockets.c#L948) the target was `char websockets_key[32];`.

In the Websocket example, [this is sent as an HTTP header](https://github.com/boazsegev/facil.io/blob/18190689b423ba547e20e1f9b9cc705d85e7ee52/lib/facil/http/websockets.c#L964-L966) and in the example code, you can print the Base64 string using `printf("Base64: %s", buffer)`.

**Comment by raminfp** [comment]
Hi @boazsegev,

now i was test lib `random` , [bscrypt_rand32](https://github.com/boazsegev/facil.io/blob/master/lib/facil/bscrypt/bscrypt/random.c#L31) this is return `uint32_t`, but i got output negative i think random number start from 0 to MAX_INT, 

can you test and answer to me? 


Thanks again,

**Comment by boazsegev** [comment]
Hi @raminfp ,

I'm not sure I understand your question.

As you probably know, [`unsigned` integers can't be negative](https://en.wikipedia.org/wiki/Integer_(computer_science)).

`uint32_t` is 32 bits long. All bits are random.

MAX_INT is 31 bits long + 1 bit reserved for the sign.

All random functions return unsigned integers, using all bits as random.

If you need a positive number in a `signed` integer, simply unset the MSB (i.e. `n & ((uint32_t)~0 >> 1)`).

B.

**Comment by raminfp** [comment]
Hi @boazsegev 

>All random functions return unsigned integers, using all bits as random.

Yes,but i see your lib negative int number


```C
printf("Random : %d\n", bscrypt_rand32());
```

```bash

[root@raminfp ramin]# ./main 
Random : -867264078  ===> negative
[root@raminfp ramin]# ./main 
Random : -425293071 ===> negative
[root@raminfp ramin]# ./main 
Random : -557765417 ===>negative
[root@raminfp ramin]# ./main 
Random : 1813086663
[root@raminfp ramin]# ./main 
Random : -1251119898 ===> negative
[root@raminfp ramin]# ./main 
Random : 1991899985

```

Best Regards,

**Comment by boazsegev** [comment]
Hi @raminfp ,

> Yes,but i see your lib negative int number

This is because of the way you call `printf`.

`printf` is a [variadic function](http://en.cppreference.com/w/c/variadic) and it doesn't know the type of the variables you pass on.

The way `printf` recognizes types is by parsing the string. `%d` means a `signed int`, which is why you're printing negative numbers when the MSB is set.

You might consider using `%u` to inform `printf` that the argument is an `unsigned int`.

You can [read more about `printf` flags here](http://en.cppreference.com/w/c/io/fprintf).

Kindly,
   B.

**Comment by raminfp** [comment]
Oops oh oh،Yes exactly I forgot, Thanks again <3
