### ISSUE TITLE
Recommendations for path/param matching

### ISSUE THREAD

**Issue by gf3** [boazsegev/facil.io#2]
Do you have any library recommendations for parameter and path matching (aside from rolling one's own with sscanf/regexp)?

**Comment by boazsegev** [comment]
I don't have any recommendations, the only one I know of is [the r3 library](https://github.com/c9s/r3)...

I also think this is a very project dependent consideration.

Personally, I would avoid both `sscanf` and regex when implementing a routing system (if possible). I find both cost more then I'd like and the routing system will be used too often for there solutions.

For example, do you intend on using a RESTful type of routing system (i.e., support paths such as `/user/(:id)`, where `(:id)` is an optional query parameter embedded in the URL)? Are you looking for a straight forward router (only string path matching)? Will you provide rewrite rules or CRUD callback mapping?

I think it might be interesting to write a RESTful routing system, perhaps with a few CRUD helpers.

I would probably tokenize the `url` and then [decode it in place](https://github.com/boazsegev/c-server-tools/blob/d1c44a9510785beab4e58ddf63513d1642bd451e/src/http/http.h#L116).

The inline parameters "array" can probably use the first byte (the `:` before the string) to mark the parameter name as either required or optional. The `'/'` byte will be replaced with NULL. 

The prefix (the fixed text part of the URL) could probably be kept as a single (untokenized) string.

However, as performant as this design might be, it will constrain the route to a `"/fixed/:required/(:optional)"` template, it couldn't support `"/fixed/:required/more_fixed/:required/(:optional)"`.

Also, there's the question of case sensitivity (for the string part of the URL, not the parameters).

Rewrite routes would be tricky, but it might be important to allow for optional data at the head of the URL such as `"/en/path..."` or `"json/path..."`.  They might require either an array of acceptable values or the use of a regexp. I would probably leave this logic for later and implement a callback instead.

Once a route's design is decided on, it's mostly a matter of implementing a HashMap and mapping any inline parameters (i.e.: `/users/1` would build the HashMap `"id" => "1"`) and query parameters.

Optionally, I would add any form POST parameters to that same HashMap (or provide functionality for that).

The form POST parsing will be difficult, especially supporting the mime-multipart format. I remember I wrote one in Ruby, it was a bit of a head ache even though Ruby took some of the workload off my shoulders.

That's as much advice as I have in me at the moment... but it all really depends on your needs.

**Comment by gf3** [comment]
thanks for the advice, i'll give it a shot and see what i come up with
