### ISSUE TITLE
Some strange libs dependencies.

### ISSUE THREAD

**Issue by kotocom** [boazsegev/facil.io#23]
//Brief about me. Newbie lnx usr. trying to write C server with blackjack and... saw you lib and it is quite lite.
//But i have fail from the start due to dependencies... and i ask you for advise.
//from the start, i tried download with script + newapp and typical way.
//e.g.
wget https://github.com/boazsegev/facil.io/archive/master.zip
unzip master.zip
cd facil.io-master/

root@ubuntu-512mb-ams2-01:~/facil.io-master# ls
CHANGELOG.md    CONTRIBUTING.md  docs      examples  LICENSE   NOTICE     scripts
CMakeLists.txt  dev              Doxyfile  lib       makefile  README.md  tests

//for case
root@ubuntu-512mb-ams2-01:~/facil.io-master# make clean
rm: cannot remove 'tmp/demo': No such file or directory
makefile:167: recipe for target 'clean' failed
make: [clean] Error 1 (ignored)
rm: cannot remove 'tmp': No such file or directory
makefile:167: recipe for target 'clean' failed
make: [clean] Error 1 (ignored)

//lets make it from the box. ...i said...
root@ubuntu-512mb-ams2-01:~/facil.io-master# make
lib/facil/core/defer.c:56:3: error: unknown type name ‘uint8_t’
   uint8_t state;
   ^
makefile:158: recipe for target 'tmp/./lib/facil/core/defer.o' failed
make: *** [tmp/./lib/facil/core/defer.o] Error 1

//nope said compiler...
//ver is
root@ubuntu-512mb-ams2-01:-/facil.io-master# gcc -v
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)

//i assumed fail of #include <sys/types.h>
root@ubuntu-512mb-ams2-01:-/facil.io-master# echo "#include <sys/types.h>" | gcc -E -x c - | grep /types.h
1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4

root@ubuntu-512mb-ams2-01: / vim /usr/include/x86_64-linux-gnu/sys/types.h
//hm... they are without needed types... i guess... strange

root@ubuntu-512mb-ams2-01: -/facil.io-master# vim lib/facil/core/defer.c
include <inttypes.h> //add //for test
include <sys/types.h>

root@ubuntu-512mb-ams2-01: -/facil.io-master# make
//this should not have happened...
lib/facil/core/types/fiobj/fiobj_str.c: In function ‘fiobj_str_readfile’:
lib/facil/core/types/fiobj/fiobj_str.c:222:45: error: ‘PATH_MAX’ undeclared (first use in this function)
   if (file_path_len == 0 || file_path_len > PATH_MAX)
                                             ^
lib/facil/core/types/fiobj/fiobj_str.c:222:45: note: each undeclared identifier is reported only once for each function it appears in
lib/facil/core/types/fiobj/fiobj_str.c:249:7: warning: implicit declaration of function ‘pread’ [-Wimplicit-function-declaration]
   if (pread(file, obj2str(str)->str, limit, start_at) != (ssize_t)limit) {
       ^
lib/facil/core/types/fiobj/fiobj_str.c:225:8: warning: unused variable ‘real_public_path’ [-Wunused-variable]
   char real_public_path[PATH_MAX + 1];
        ^
makefile:158: recipe for target 'tmp/./lib/facil/core/types/fiobj/fiobj_str.o' failed
make: *** [tmp/./lib/facil/core/types/fiobj/fiobj_str.o] Error 1

//first guess it could be limits...
root@ubuntu-512mb-ams2-01: -/facil.io-master# echo "#include <limits.h>" | gcc -E -x c - | grep /limits.h
1 "/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/limits.h" 1 3 4
1 "/usr/include/limits.h" 1 3 4
1 "/usr/include/linux/limits.h" 1 3 4

//but they present... what is happening... something going wrong...
//i don't know why something is wrong with libs and dependencies... or they are different... 
//so i ask you for advise how should i solve this? Do i need do download some extra libs files? Is this something wrong with distro?

**Comment by boazsegev** [comment]
Hi @kotocom ,

Thank you very much for opening this issue! 🙏🏻

Indeed there was an issue with `gcc` compatibility on Linux (I didn't notice I ran only the `clang` test).

I released an update.

To create a new application, run the following script from your terminal (see [the README here](https://github.com/boazsegev/facil.io#starting-a-new-project-with-facilio)):

    bash <(curl -s https://raw.githubusercontent.com/boazsegev/facil.io/master/scripts/new/app) appname

Please note that the `master` branch is the development branch and that the latest release can be accessed using the [Releases link](https://github.com/boazsegev/facil.io/releases).

Thanks again!
   Bo.

**Comment by kotocom** [comment]
That helped a lot and works, thanks. ＼(^-^)／
