### ISSUE TITLE
bash issues under Linux

### ISSUE THREAD

**Issue by yandrey** [boazsegev/facil.io#27]
it works like this under Ubuntu:
```
bash <(curl -s https://raw.githubusercontent.com/boazsegev/facil.io/master/scripts/new/app) testapp
* Creating testapp
https://api.github.com/repos/boazsegev/facil.io/tarball/v.0.6.0.beta
rm: cannot remove 'src': No such file or directory

```
next
```
~/testapp$ make
/bin/sh: 1: Syntax error: Bad fd number
/bin/sh: 1: Syntax error: Bad fd number
/bin/sh: 1: Syntax error: Bad fd number
/bin/sh: 1: Syntax error: Bad fd number

```
maybe because of >& instead of &> ? Not sure. Just tried once and the output looks a bit weird

**Comment by boazsegev** [comment]
Hi @yandrey,

Thank you for opening this issue.

These error messages are mostly related to testing output. The messages don't effect your facil.io app.

I updated the testing output so it's redirected to /dev/null and I avoided the newer bash 4 flag `&>` .

The fix will be available starting with the next facil.io release.

Thanks again 👍🏻
   Bo.
