### ISSUE TITLE
How to send data image base64 in socket in http?

### ISSUE THREAD

**Issue by ahmedjavad** [boazsegev/facil.io#29]
Hi,

Thanks for repo, 

I have a question, How to you convert a image (.png) that is a large character to base64 from clinet side and send data in the socket to server and convert base64 image (.png) of server side  in C in facil ? how to handle to buffer large character?

Thanks,

**Comment by boazsegev** [comment]
Hi @ahmedjavad ,

Thank you for your interest in facil.io.

I'm not sure I understand where you might be stuck.

Client side conversions (I'm assuming a browser) would be performed using [JavaScript Base64 encoding/decoding](https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding).

Server side decoding can use [facil.io's Base64 encoding/decoding functions](https://github.com/boazsegev/facil.io/blob/3d8616b093039179520793e419e1e4e1d8eba936/lib/facil/core/types/fiobj/fio_base64.h#L21-L58).

Could you provide the code you attempted to use, so I can see where you're experiencing an issue?

Kindly,
   Bo.

P.S.

[StackOverflow](https://stackoverflow.com) is often a better place to ask questions, as you will receive attention from more developers and your questions might be answered sooner.

**Comment by ahmedjavad** [comment]
@boazsegev Thanks for reply,

I write web socket with HttpPost in the socket, 

I know but i don't know how to read image file to base64 in C without use libpng 
(https://github.com/glennrp/libpng),

```C
# client.c
int client() { 
    // read image path 
     char * img = "path/1.png";

   // now how to read image file and convert to base64 ???
    
   // init socket
   while (){
         // sening data until buffer  = '\0'
  }

  // close socket

  return 0;
}
```

**Comment by boazsegev** [comment]
It looks like your code is in a very early draft.

Are you using facil.io? If so, how? (I don't see it in your question).

Is the client in C as well?

Are you trying to use WebSockets or are you trying to use HTTP POST (these are two different things and it's usually one **or** the other for the client)?

Please notice that sockets and WebSockets are two different things. Sockets are the lower level TCP/IP sockets and WebSockets is a name of a specific protocol (it starts out as HTTP and uses a specific message framing requirement to allow browsers and servers to send messages to each other without the restrictions of HTTP).

If you're using HTTP POST you don't need to convert the file data to Base64.

Using facil.io, you can do both (this is just a draft, not tested code, it sends the file using HTTP POST):

```c
/* client.c */
#include "facil.h"

#include "fio_base64.h"
#include "http.h"
#include <signal.h>

static void post_file(http_s *h) {
  if (h->status == 0) {
    /* a connection was established, but nothing has happened so far. */

    h->method = fiobj_str_new("POST", 4);      // Set method
    h->path = fiobj_str_new("/", 1);           // Set path
    h->method = fiobj_str_new("image/png", 9); // Set content type

    if (1) {
      /* without converting to Base64 */
      if (http_sendfile2(h, "path/file.png", 13, NULL, 0)) {
        // the file wasn't found or couldn't be sent
      }

    } else {
      /* Base64 requires us to load the image to memory */
      // read the file
      FIOBJ body = fiobj_str_readfile("path/file.png", 0, 0);
      if (!body) {
        /* failed to open file */
        return;
      }
      // require memory - this will update the internal string object
      fiobj_str_capa_assert(body, ((fiobj_obj2cstr(body).len / 3) * 4) + 4);
      // convert to Base64 in place
      fio_cstr_s buff = fiobj_obj2cstr(body);
      int new_len = fio_base64_encode(buff.data, buff.data, buff.len);
      fiobj_str_resize(body, (size_t)new_len);
      buff = fiobj_obj2cstr(body); // the internal string may have moved.
      http_send_body(h, buff.data, buff.len);
      fiobj_free(buff);
    }
    return;
  }
  FIOBJ str = http_req2str(h);
  fprintf(stderr, "Got the following response:\n%s\n",
          fiobj_obj2cstr(str).data);
  fiobj_free(str);
}

static void stop_facil(http_settings_s *settings) {
  kill(0, SIGINT);
  (void)settings;
}

int main(int argc, char const *argv[]) {
  /* code */
  http_connect("http://www.example.com/", .on_response = post_file,
               .on_finish = stop_facil);
  facil_run(.threads = 1);
  return 0;
  (void)argc;
  (void)argv;
}
```

**Comment by boazsegev** [comment]
> How to handle and read image file fiobj_str_readfile ? i have problem with read image file format to base64 in the memory client side and write base64 string to image file in server side!?

The file format doesn't matter. Your application doesn't care about the content of the image, only it's binary data.

You should open the file (using the windows equivalent of [`open`](http://man7.org/linux/man-pages/man2/open.2.html) or [`fopen`](http://man7.org/linux/man-pages/man3/fopen.3.html)) and read it's raw content into a buffer.

Afterwards you should Base64 encode the buffer.

>  > Are you using facil.io?

> No, because this is for windows,

This repo is for facil.io.

If you have questions that aren't about facil.io, please ask them in [StackOverflow.com](https://stackoverflow.com).
