### ISSUE TITLE
Is this compatible with NGINX NCHAN? which example is most fit to this integration

### ISSUE THREAD

**Issue by Taymindis** [boazsegev/facil.io#30]

**Comment by boazsegev** [comment]
I didn't try it, but from what I understand about NginX Nchan:

1. facil.io is extendible. The pub/sub layer can be extended using pub/sub engines (authoring an engine for Nchan is definitely possible) and it can be edited (this is one of the advantages of a source-code library).

   This should allow facil.io to connect to nginx Nchan as either a client (a proxy subscriber) or a distributer.

1. Nchan can use Redis to sync clusters together, meaning that facil.io and nginx can share the Redis pub/sub backend making them compatible.

   This could allow facil.io applications to behave as if they were an Nchan node.

**Comment by Taymindis** [comment]
Thanks !
