### ISSUE TITLE
Can we get a more complete explanation for the C11 requirement?

### ISSUE THREAD

**Issue by seltzy** [boazsegev/facil.io#32]
This library is pretty sweet. Thanks for making it!

I'm evaluating the portability of this library. The README made it sound like there are only a few C11 features being used. If it's not too much work it would be great to have support for C99. There are way more compliant compilers for that standard. If that's not going to be an easy task, can the reasons behind that be elaborated more in the README or some other relevant part of the repo?

Thanks :)

**Comment by boazsegev** [comment]
Hi @seltzy ,

Thank you for opening this issue.

The only C11 feature I intentionally use is the Anonymous Unions (some repeated typedefs sneaked in, but they are easily removed).

Avoiding this feature is only hard in the sense that it will introduce breaking changes to the API.

Anonymous Unions are used both used for backwards compatibility (where structure member names were changed and the old names are still supported) and as part of the API (I offer "name arguments" using macros and these Anonymous Unions are used in some exclusive options).

Do you think the C99 compatibility concern is worth the inconvenience / API breakage of named unions?

Isn't it better to demand more of our compilers?

While I'm asking this, I'm also working on version 0.7.0 which will introduce some API breakage anyway (and the Anonymous Unions feature should help bridge some of the gaps)... so I don't really mind it all that much, I just want to make life easier for developers and Anonymous Unions seem like a good way to do that.

**Comment by seltzy** [comment]
I see. Thank you for answering my question. If it's to make the API easy to use it's not worth sacrificing. I don't see too many C projects explicitly requiring anything higher than C99 so it seemed like an unusual requirement at first.

**Comment by boazsegev** [comment]
@seltzy , thanks for your feedback.

I appreciate your opinion, since I never really gave it enough thought. I started this project with my own requirements in mind, so I didn't think about some things that might be more relevant for a public project.

Just to make sure I understand correctly, you believe that using the C11 Anonymous Unions feature for API convenience is worth the requirement (a C11 compiler)...?

Kindly,
  B.

**Comment by seltzy** [comment]
Probably. I haven't used the API enough to know for sure, but if there are a lot of users who would have things break it may not be worth it. I think the real question is, how much of a priority is portability?

**Comment by boazsegev** [comment]
The API was updated and the 0.7.0 version of the library (edge version, un-released) is C99 compatible.

I'm closing the issue.

Thank you @seltzy for your input 🙏🏻
