### ISSUE TITLE
SSL / TLS library

### ISSUE THREAD

**Issue by frink** [boazsegev/facil.io#37]
I know one of the main concerns for SSL/TLS is that it doesn't gonk the license. Most SSL/TLS is sadly CPL cancer which is a problem for keeping facil.io MIT. After a bit of Googling I came upon BearSSL which is MIT and appears to meat the needs of simple, client and server side implementations. Without much overhead in its own right.

https://bearssl.org/index.html

You could either pull it in as a compiled dependency or pull in the bits and pieces of code that you want to salvage without causing license problems. Seems like it might work...

**Comment by boazsegev** [comment]
@frink , thanks👍🏻

I looked over the library a while back, it was in Beta... but it seems a release version was released on August 14th 🎉

I guess BearSSL will be the one I'll start with.

The license was an issue as well as trying to figure out some API design choices. I suspect now that the license concern can be solved, I should bear down on the design and implement the SSL/TLS layer.

Thanks 👍🏻

**Comment by boazsegev** [comment]
@frink, 

I'm still planning to add BearSSL support at some point, but for now OpenSSL (>= 1.1.0) is supported. I believe BearSSL's approach is superior, but OpenSSL is prevalent.

I'll go ahead and close the issue even though the license issue (MIT) won't be resolved until I author support for BearSSL.

Kindly,
   Bo.

**Comment by frink** [comment]
That works as long as you don't compile static. If you're trying to do some rump kernel voodoo or something strange like that it could become a license pollutant. I agree that BearSSL has a superior approach and for something like Facil if probably actually makes more sense than most other use cases.

However, I also understand the constrained resource limit and the over abundance of reliance on OpenSSL. (which I trust less and less every release...) With everyone from Apache and Nginx to H2O and Mongoose depending on OpenSSL it's probably a simple solution for now. But like I said, it doesn't work for proprietary code if static compilation is the aim.

Thanks for getting back to me!

Cheers!
