### ISSUE TITLE
Logo aspect ratio

### ISSUE THREAD

**Issue by benjcal** [boazsegev/facil.io#39]
https://github.com/boazsegev/facil.io/blob/226ee90861a615f3a5149204adf48aff92b8982e/docs/_SOURCE/assets/styles/main.css.scss#L397

I've been trying to figure out why not include the logos on `layout.html.slim` as `img` tags but include them instead in the css... the aspect ratio is all wrong...
Working on a solution...

**Comment by boazsegev** [comment]
Hi @benjcal , thanks for your input and observation.

I guess `img` tags could work. I have a tendency to move as much of the design considerations as I can to the CSS layer.

However, I imagine any aspect ratio issues could be fixed using CSS...

... but I didn't notice any aspect ratio issue. Maybe it's just me or a specific browser / device, but I'm not sure I see it.

...?

B.

**Comment by boazsegev** [comment]
I think I see what you mean - you've got eyes like a hawk, I didn't even notice what you saw so clearly. The issue might have appeared differently on different systems.

I think I fixed it, but since your eyesight is clearly better, I'd be thankful if you could let me know.

**Comment by boazsegev** [comment]
We can close this, right?

**Comment by benjcal** [comment]
yeah, I think we can close it. Sorry for the crazy long delay 😄
