### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [boazsegev/facil.io#43]
Would you like to [add more error handling for return values](https://github.com/boazsegev/facil.io/blob/b6c8db7a06cc17a921cc4a36470f55760373400e/tests/malloc_speed.c#L148 "Update candidate: main()") from [functions like “pthread_create”](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_create.html "Thread creation")?

**Comment by boazsegev** [comment]
The answer would always be "yes". Error testing is always preferred.

This case is very low priority. It's a `malloc` vs. `fio_malloc` speed testing snippet. It isn't part of the framework code. I guess I was rushing through it.

I'd be happy to get it fixed (just exit on error), but I prefer to focus on the productive parts.

Thanks!
☺️

**Comment by boazsegev** [comment]
Done 👍🏻

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/boazsegev/facil.io/commit/fb1c561a48724c97ba6901f428b84feff9976a43 "Addition of error handling").
