### ISSUE TITLE
facil.io as single source file

### ISSUE THREAD

**Issue by chertov** [boazsegev/facil.io#46]
Hi! Is it possible to build facil.io library as single source file, like "the amalgamation" sqlite3.c?
Thanks!)

**Comment by boazsegev** [comment]
Hi @chertov ,

Thank you for your interest.

you can dump everything to a single `all` folder (or 2 folders, `src` and `include`) using `make libdump`, but you'll still get all the files separately.

At the moment, creating an amalgamation file will be impossible, for 2 reasons:

1. The TLS extension support required weak functions in the core library.

    The core facil.io library uses `weak` functions that can be overridden. This design allows the 2 file core library (`fio.h` and `fio.c`) to be compiled without any extensions (no TLS, HTTP, WebSockets or Redis support, no FIOBJ types).

    Specifically, the TLS extension (which can be safely deleted and everything will still compile) is required [this design](https://github.com/boazsegev/facil.io/blob/cc368d09a7cf34eba0e3961f8fbb71aecd914e2a/lib/facil/fio.c#L4283-L4355) in order to allow TLS integration into the `fio_connect` and `fio_listen` functions.

2. Some code, usually code from `fio.h`, is included more then once using different semantics.

    To allow for this, I would need to re-write the Core Strings and the Linked List implementation to use the same macro based approach as the Core Array and HashMap implementations.

Removing the `weak` function approach will probably be easier, I can do it using the compile-time macros (i.e., `HAVE_OPENSSL`) which are already used by the TLS implementation.

However, updating the core string library and the linked lists will break the current API, so it's a big change.

I'm curious - why would you want to do this?

Bo.
