### ISSUE TITLE
Read content from file descriptor

### ISSUE THREAD

**Issue by recoilme** [boazsegev/facil.io#5]
When request body more then 1024 - it stored data in some tmp file?
May you please explain where i may find this file and how to read data from it
Thank you

**Comment by boazsegev** [comment]
I'm a bit busy today, I'll try to be short and fast, if I don't answer everything, I'll write more when I can.

Sometimes a request's body will be in a temporary file.

This isn't only about the body size, but also about pack size and client behavior.

Theoretically, depending on client behavior, you can have an 8 byte body in a temporary file.

The temporary file is accessible using it's `fd` through `request->body_file`. Notice: this is **NOT** a `FILE *`, but an `int`.

You can (and should) check for the body type using:

```c
if(request->body_str) {
  // body in bytes
} else if(request->body_file) {
  // body in temporary fd
} else {
  // no body?
  if(request->content_length) {
     // weird... error? this shouldn't happen
  }
}
```

The request will use a temporary `fd` if the body takes more than a single TCP/IP packet.

Most TCP/IP packets are ~1050 bytes long (depends on the MTU value).

Most browsers will send the headers in one or more packets and then the body in one or more packets, where the body always starts with a new TCP/IP packet.

However, some clients / browsers will send it all together (so the body might start on the last 2 bytes of the second packet).

If the parsing event encounters a split body (a body that takes more than a single TCP/IP), a new temporary file will be created.

I should probably change this behavior, but it made the parsing simpler...

**Comment by boazsegev** [comment]
I hope this answers your question?

**Comment by recoilme** [comment]
Thank you,  I understand! I think it file number and try to find it in current folder,  sorry

**Comment by boazsegev** [comment]
I'm closing this issue because the HTTP request / response `body` type was unified under the `FIOBJ` type system, abstracting away the differences between temporary file storage and in memory storage.

This make reading the `body` (if there is a `body`) very easy using the `fiobj_data_*` API.
