### ISSUE TITLE
Attempting to free stack allocated channel_s object

### ISSUE THREAD

**Issue by adamansky** [boazsegev/facil.io#56]
Version `0.7.0.beta8`

When building a release with `gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0` I see the following:

```
In function ‘fio_channel_free.part.26’,
    inlined from ‘fio_ch_set__insert_or_overwrite_.constprop’,
    inlined from ‘fio_filter_dup_lock_internal’ at lib/facil/fio.h:6127:10,
    inlined from ‘fio_filter_dup_lock’ at lib/facil/fio.c:5383:10,
    inlined from ‘fio_subscribe’ at lib/facil/fio.c:5455:8:
lib/facil/fio.c:5151:3: warning: attempt to free a non-heap object ‘ch’ [-Wfree-nonheap-object]
   free(ch);
   ^~~~~~~~
In function ‘fio_channel_free.part.26’,
    inlined from ‘fio_ch_set__insert_or_overwrite_.constprop’,
    inlined from ‘fio_filter_dup_lock_internal’ at lib/facil/fio.h:6127:10,
    inlined from ‘fio_channel_match_dup_lock.isra.67’ at lib/facil/fio.c:5416:14,
    inlined from ‘fio_subscribe’ at lib/facil/fio.c:5457:8:
lib/facil/fio.c:5151:3: warning: attempt to free a non-heap object ‘ch’ [-Wfree-nonheap-object]
   free(ch);
   ^~~~~~~~
In function ‘fio_channel_free.part.26’,
    inlined from ‘fio_ch_set__insert_or_overwrite_.constprop’,
    inlined from ‘fio_filter_dup_lock_internal’ at lib/facil/fio.h:6127:10,
    inlined from ‘fio_channel_dup_lock.isra.68’ at lib/facil/fio.c:5396:14,
    inlined from ‘fio_subscribe’ at lib/facil/fio.c:5459:8:
lib/facil/fio.c:5151:3: warning: attempt to free a non-heap object ‘ch’ [-Wfree-nonheap-object]
   free(ch);
```

**Comment by boazsegev** [comment]
Hi @adamansky ,

Thank you very much for opening this issue.

I can't replicate the issue at the moment, I'll need to upgrade my `gcc` and VM for that, which I'll try to do tonight.

In the meantime, I wonder - could this be a compiler error?

[The stack memory is assigned a high reference count](https://github.com/boazsegev/facil.io/blob/e649091a1de13ef4a83e1b3911dcdc93d389a7ea/lib/facil/fio.c#L5381), preventing the [`fio_channel_free` function from freeing stack allocated objects](https://github.com/boazsegev/facil.io/blob/e649091a1de13ef4a83e1b3911dcdc93d389a7ea/lib/facil/fio.c#L5149-L5151).

The result is that stack objects are either ignored or that they are ["copied" to the heap](https://github.com/boazsegev/facil.io/blob/e649091a1de13ef4a83e1b3911dcdc93d389a7ea/lib/facil/fio.c#L5130-L5144) (with a new reference count), but never freed.

In this case, the `if (fio_atomic_sub(&ch->ref, 1))` statement is always true (always 7, which is luckier than always -1, but produces the same result).

Did I miss something?

Kindly,
   Bo.

**Comment by boazsegev** [comment]
I installed GCC 7... which installed version 7.4.0 (`gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~16.04~ppa1)`)...

...the warning doesn't seem to pop up. I can't reproduce.

Perhaps it's a GCC issue that was fixed?

**Comment by adamansky** [comment]
Hi Boaz! I think compiler is quite objective here, for example
```
In function ‘fio_channel_free.part.26’,
    inlined from ‘fio_ch_set__insert_or_overwrite_.constprop’,
    inlined from ‘fio_filter_dup_lock_internal’ at lib/facil/fio.h:6127:10,
    inlined from ‘fio_channel_match_dup_lock.isra.67’ at lib/facil/fio.c:5416:14,
    inlined from ‘fio_subscribe’ at lib/facil/fio.c:5457:8:
```
Where `ch` is placed on stack in `fio_channel_match_dup_lock()` and then used in `fio_channel_free()` It seems the compiler is not smart enough to prove that `fio_atomic_sub(&ch->ref, 1)` will be always true in runtime. May be `7.4.0` is able to derive it :)

Yes I see your comment: `/* avoid freeing stack memory */` in https://github.com/boazsegev/facil.io/blob/master/lib/facil/fio.c#L5395

So seems to be no problems here. Thank you!
