### ISSUE TITLE
Memory leak in example code?

### ISSUE THREAD

**Issue by sunqingyao** [boazsegev/facil.io#58]
I'm on macOS 10.14 so I cannot use Valgrind to verify my concern, but please take a look here.

https://github.com/boazsegev/facil.io/blob/71eeb028b741d4512886be4c17bb861c88918fee/examples/raw-echo.c#L74-L89

On L77, you allocated a chunk of memory for `echo_proto`, but on the very next line, you point it to a compound literal with [automatic storage duration](https://stackoverflow.com/questions/21882564/what-is-the-lifetime-of-compound-literals-passed-as-arguments), discarding its previous value. I think this might cause a memory leak because you never called `free`.

To make thing even more confusing, there appears to be a [related compiler bug](https://stackoverflow.com/q/47691857/5399734).

**Comment by boazsegev** [comment]
@sunqingyao ,

Thank you opening this issue and asking questions about the code and the documentation.

I think what happened is that you missed the memory dereferencing in L78.

The memory pointer isn't overwritten. The content of the compound literal is copied to the allocated memory when the pointer is dereferenced. This is similar to writing:

```c
echo_proto->on_data = echo_on_data;
echo_proto-> on_shutdown = echo_on_shutdown;
/* ... */
```

Please let me know if you have any further questions. I will be happy to answer them.

Kindly,
   Bo.

**Comment by sunqingyao** [comment]
Yeah, you're right, and this is a neat trick. Thanks for answering my question!
