### ISSUE TITLE
Adding a void *udata field to fio_protocol_s

### ISSUE THREAD

**Issue by sunqingyao** [boazsegev/facil.io#59]
I think it would be nice to have some data private to each connection, just like Flask's request context. The most obvious way to do this is by adding a `void *udata` field to `fio_protocol_s`.

A typical use case is attaching a database instance `db` to each connection, so that during a request, references to `db` will always refer to the same object. Also, this `db` instance will be closed automatically at the end of the request with the help of `on_close`.

**Comment by boazsegev** [comment]
I’m on my phone, so I’ll write a longer answer later.

The facil.io library assumes a simple OOP model.

The idea is to include the protocol structure as the first element in a larger structure and then cast the pointers to the correct type.

Have a look at the raw HTTP example for an example of how to do this:

https://github.com/boazsegev/facil.io/blob/master/examples/raw-http.c

**Comment by boazsegev** [comment]
Hi @sunqingyao ,

I promised you a longer answer.

The use of `udata` pointers is very common, especially when you don't control the memory allocations and it's a good approach.

However, `udata` uses an extra level of indirection, **resulting in higher cache misses in the CPU and reduced performance**.

For this reason, when the user can control the memory allocation, facil.io prefers an OOP model that uses pointer offsets and structures to add user data.

The `fio_protocol_s` allocation is a classic situation where the user is in total control over the allocation and an OOP approach would improve performance.

The most simple way to add user data to a protocol, is to place a protocol object as the first element in a new `struct`. This results in pointer offset 0, which means that it's safe to cast between the two types.

For example:

```c
typedef struct {
  fio_protocol_s protocol; /* all protocols must use this callback structure */
  char my_buffer[255];
} my_protocol_s;

my_protocol_s * my_p = malloc(sizeof(*p));
fio_protocol_s * fio_p = &my_p-> protocol;
my_protocol_s * my_p2 = (my_protocol_s *) fio_p;
if(fio_p == my_p2) { printf("this is always true"); }
```

This technique can be seen in [the raw HTTP example](https://github.com/boazsegev/facil.io/blob/d4ee13109736e6df7548744ab05efeb9aa645614/examples/raw-http.c#L55-L71) where [casting is used](https://github.com/boazsegev/facil.io/blob/d4ee13109736e6df7548744ab05efeb9aa645614/examples/raw-http.c#L266) to retrieve the pointer to the user-data.

This approach saves an indirection and improves performance.

Note that pointer arithmetics can be used as well, if performed correctly. The protocol object doesn't have to be the first element (although it's far more convenient).

In that same example, [pointer arithmetics is used to retrieve the protocol object from a pointer to the HTTP parser object](https://github.com/boazsegev/facil.io/blob/d4ee13109736e6df7548744ab05efeb9aa645614/examples/raw-http.c#L74-L76). This shows how to retrieve a "parent" object even when the pointer isn't a pointer to the first element in the parent.

P.S.

I think this is probably something I should add to the library's overview when I update the documentation.
