### ISSUE TITLE
From Project 3: MIT -> ISC

### ISSUE THREAD

**Issue by frink** [boazsegev/facil.io#62]
https://github.com/boazsegev/facil.io/projects/3

_These are equivalent licenses but ISC has more modern language. For most commercial projects BSD, MIT and ISC licenses are thought of as identical since they each can be included in commercial products ad nauseum._

- MIT probably has more "brand recognition" than ISC. It is the current favorite of most web frameworks and technologies - so better understood by your target audience.
- ISC is considered easier to read with more modern legalese.

_I'm not sure if you gain anything by switching and may scare off some people in the web world less familiar with the ISC (since it's newer). I try to keep things simple in my projects with either, MIT, LGPL or GPL. These are the household names. BSD gets confusing because they can't decided whether it's 2, 3 or 4 clauses._

Bottomline: _I won't waste time on this._

You'll lose more people than you gain on the switch and it doesn't change anything legally other than MIT having more case law because it's an older license...

**Comment by boazsegev** [comment]
@frink ,

You're right. Although I love the simpler language, I came a similar conclusion, so I didn't make any progress with this.

Well, the new `fio-stl.h` file does say: `License: ISC / MIT (choose your license)` , but that's about as far as I got :)
