### ISSUE TITLE
Got an error from running your test.

### ISSUE THREAD

**Issue by squidfarts** [boazsegev/facil.io#68]
I am trying to run your unit test and I get this.

![89F2D3DC-BB5D-49CD-AD95-89A3C9933E60](https://user-images.githubusercontent.com/42789598/60386885-19a7cf80-9a50-11e9-945b-e8167301396b.jpeg)

**Comment by boazsegev** [comment]
@squidfarts ,

Thank you for opening this issue.

However, just to clarify:

1. The only tests that test facil.io's integrity are perforrmed by the `tests/tests.c` file.

    All other tests are for performance or algorithm testing, such as testing the memory allocation speed, randomness in the random algorithm (improved in version 0.8.0), etc'.

2. The `xxhash` dependency can be downloaded from [the `xxhash` repo](https://github.com/Cyan4973/xxHash) and it can be skipped by setting `-DTEST_XXHASH=0`.

    To perform the collisions test you might also require a collision dictionary file that contains words used for collision testing. The default dictionary file name is `words.txt`, but any other file can be selected using the command line (`-d <filename>`).

    You can possibly download [a simple dictionary from here](https://github.com/dwyl/english-words), or perform a quick search for dictionary attack lists. I found one almost 1.8GB (84,314,684 words) long just for fun. Took about 20GB of memory to run the tests and I learned nothing.

3. As a side note: you can perform the tests using the `make` build command with either `test`, `test/optimized`, `test/collisions`, `test/c99` or `test/poll` (each testing something else).
