### ISSUE TITLE
 Whether daemons are supported

### ISSUE THREAD

**Issue by immortalChensm** [boazsegev/facil.io#83]

**Comment by boazsegev** [comment]
Hi @immortalChensm ,

There are many ways in which this question can be understood... I'll try to answer, but if I misunderstood, please correct me.

### Can a facil.io program run as a daemon?

Yes, every program compiled on a Xnix system (linux / unix) can be executed in daemon mode from the terminal or from other programs.

This can be easily performed by adding `&` to the command line. i.e.:

```bash
$ ./tmp/fio_app -t1 -www ./ &
```

### Can a facil.io be used to author a network daemon process?

This may require changes to the source code. Also, I haven't tested this I just add `&`  to the command line.

In general, during startup, facil.io will collect it's own process ID and save it as the "master" process ID.

The cached data is used to manage worker processes (vs. the master process).

This code can be "moved" / copied to the `fio_start` function in or order to allow the `fio_start` function to be called from a child process (thus updating the cached identity of the master processes).

### Zombie Handling

The [`fio_reap_children`](https://github.com/boazsegev/facil.io/blob/c1306722fd84a23447671619fc76eb8a11a6cb39/lib/facil/fio.h#L1000-L1004) function allows facil.io to automatically reap child processes when the OS or other code doesn't manage this action. This may be required when running facil.io within docker with certain provisions).

**Comment by boazsegev** [comment]
P.S.,

If you're using facil.io as a single processes (no "workers"), you can call `fio_start` from a forked process (allowing you to author a network daemon).

**Comment by immortalChensm** [comment]
Well, I mean, does it support daemon process 
add & to the command terminal can't run as a daemon process 
when i close terminal will send a SIGPIPE signal

**Comment by boazsegev** [comment]
Hi @immortalChensm ,

Thank you for explaining your issue.

When you close the terminal, `stdout` and `stderr` are closed (since, by default, they are connected ted to the terminal).

In order to avoid `SIGPIPE`, you will need to redirect the logging to a file or to `/dev/null` (no logging).

This is easily done using the `>>` operator (in bash).
i.e.:

```bash
./tmp/fio_app -t1 -www ./ >> log_file 2>&1 &
```

However, I didn't test it out myself. Let me know how it works :)

Kindly,
   Bo.

**Comment by boazsegev** [comment]
Closing after [improving forked daemon support in the 0.8.0 branch](https://github.com/boazsegev/facil.io/blob/b07db6231ad5e1a2668a3fe9b0614eb3f48dfbbf/lib/facil/fio.c#L3664).
