### ISSUE TITLE
How to compile facil.io

### ISSUE THREAD

**Issue by raminfp** [boazsegev/facil.io#9]
Hi,

i'm not sure, how to compile `facil.io`,because on your docs any point about this,

```bash
[root@raminfp facil.io]# ls
CHANGELOG.md  CMakeLists.txt  dev  docs  Doxyfile  examples  lib  LICENSE  makefile  NOTICE  README.md  scripts  tests
[root@raminfp facil.io]# 
[root@raminfp facil.io]# make
Assembler messages:
Fatal error: can't create tmp/./lib/core/defer.o: No such file or directory
makefile:114: recipe for target 'tmp/./lib/core/defer.o' failed
make: *** [tmp/./lib/core/defer.o] Error 1

```

please help for it,

Thanks,
Ramin

**Comment by boazsegev** [comment]
Hi Ramon,

Thanks for pointing this out!

I'm away from the computer, I'll write more later.

Try running `make clean` to build the folder structure before running `make run`.

facil.io is a source code library. Theoretically I assumed people would just copy the features they're using into their own project.

B.

**Comment by boazsegev** [comment]
Hi @raminfp ,

Thanks again for opening this issue!

I've updated the README to reflect your question. It reads:

---

[facil.io](http://facil.io) is a source code library, so it's possible to simply copy the source code into a new project.

[facil.io](http://facil.io) also supports both `git` and CMake submodules.

However, when starting a new project, it's often easiest to simply fork this project and place your own source code in the `dev` folder, perhaps updating the `makefile` to make it more compatible with your project's folder structure.

When forking this project, please run `make clean` to build the `tmp` folder structure used for compiling. Unless `make clean` is called, the compiler / linker will fail with a `No such file or directory` error.

**Comment by raminfp** [comment]
@boazsegev Your Welcome, Thanks for repo!

**Comment by boazsegev** [comment]
@raminfp ,

You're welcome 😊 

Just a quick note: I noted you're using the version in the *master* (development) branch.

Although this is the edge version with the most fixes and effort put into it... it isn't stable.

I should probably change the branching scheme as `facil.io` evolves, since I also push commits to backup my work, which means some things in the master branch might suddenly break as I'm rewriting them (or while I rewrite some other part and didn't test the changes yet).

Once version 0.5.0 is released (the upcoming release), I recommend that you consider using the stable releases (tagged) instead.

B.

**Comment by raminfp** [comment]
@boazsegev sure,Thank you so much, i see your code (libs) very interesting and i use your libs :) , so i was unable to find you twitter do you have twitter account?

Thanks,

**Comment by boazsegev** [comment]
@raminfp , I'm happy you're enjoying the libraries.

My twitter account is [@bowildmusic](https://twitter.com/bowildmusic) ... I'm a musician and I don't really use my Twitter account for anything. I hope I'll use it more often in the future :-)

**Comment by raminfp** [comment]
OMG, Interesting! You have time for programming and music! Excellent talent!

**Comment by boazsegev** [comment]
No time... just tons of sleepless nights doing both things that I love :-)

I'm just  dropping a note to let you know I finished fixing up and releasing version 0.5.0. You'll also find a stable branch was created.

**Comment by raminfp** [comment]
Thank you so much @boazsegev  

>No time... just tons of sleepless nights doing both things that I love :-)
 
Nice job, good luck 👍 

Best Regards,
