### ISSUE TITLE
Error in http_sendfile using an accessible file

### ISSUE THREAD

**Issue by milnomada** [boazsegev/facil.io#90]
I'm sending files over http using facil.io  
This code:

```c
int size = get_file_size(filepath);
FILE *fp = fopen(filepath, "r");
if(!fp) {
    FIO_LOG_WARNING("Can't read file");
    return 1;
}
http_sendfile(h, fp, size, 0);
```
shows **this error** in logs:
```sh
DEBUG (lib/facil/http/http1.c:671): HTTP parser error.
```

This message is shown by curl, 
```sh
curl: (18) transfer closed with 1940 bytes remaining to read
````
where 1940 bytes is the `size` of the requested file.

-----

Instead, the following works great:

```c
FILE *fp = fopen(filepath, "r");
if(!fp) {
    FIO_LOG_WARNING("Can't read file");
    return 1;
}
int size = get_file_size(filepath);
char buffer[size];
fread(buffer, size, 1, fp);
fclose(fp);

char *ext = get_filename_ext(filepath);
http_set_header(h, HTTP_HEADER_CONTENT_TYPE, http_mimetype_find((char *)ext, strlen(ext)));
http_send_body(h, &buffer, size);
```

Am I missing something in the `http_sendfile` code?
Why could it be giving this error?

Thanks for any help

**Comment by boazsegev** [comment]
Hi @milnomada ,

Thank you for opening this issue and asking your question.

I'm not such which version of facil.io you might be using, but I'll assume it's version 0.7.x.

As you might notice in the [`http_sendfile` documentation](https://facil.io/0.7.x/http#http_sendfile), facil.io doesn't support the `FILE *` type, instead the function accepts an `int` (file descriptor).

In fact, for your specific use case, it seems that [the `http_sendfile2` function](https://facil.io/0.7.x/http#http_sendfile2) would work better.

The code might look something like this:

```c
if(http_sendfile2(h, filepath, size_t strlen(filepath),
                   NULL, 0)) {
   http_send_error(h, 404);
    FIO_LOG_WARNING("Can't read file %s", filepath);
    return 1;
}
return 0;
```

Of course, if `filepath` is a URL encoded file path that was submitted from the internet, it should be sanitized. In which case, use:

```c
if(http_sendfile2(h, NULL, 0,
                   filepath, size_t strlen(filepath),)) {
   http_send_error(h, 404);
    FIO_LOG_WARNING("Can't read file %s", filepath);
    return 1;
}
return 0;
```

If you have a public folder that is the "root" folder, you might use that path as the prefix:

```c
if(http_sendfile2(h, PUBLIC_FOLDER_PATH, strlen(PUBLIC_FOLDER_PATH),
                   filepath, size_t strlen(filepath),)) {
   http_send_error(h, 404);
    FIO_LOG_WARNING("Can't read file %s", filepath);
    return 1;
}
return 0;
```

**Comment by boazsegev** [comment]
@milnomada ,

I hope my answer solved your issue. If so, I think we can close the issue.

Please feel free to post any future questions here or on StackOverflow (tag me as `@Myst`).

Kindly,
   Bo.

**Comment by milnomada** [comment]
Hi @boazsegev 

Thanks for your fast reply.
It works as you proposed, it was an issue with FILE as you mentioned.

facil.io is a great tool
