### ISSUE TITLE
how to handle multipart form using facil.io

### ISSUE THREAD

**Issue by rajesh-krishnan** [boazsegev/facil.io#93]
Thank you for making this nice web application framework package available. 

I am working on a simple web application which posts a multipart form, with three string fields, a file upload, and a submit button. I am able to get the body and print it (or print the request header), but I am not able to get the individual name-value pairs, after the parsing.

Does facil.io have support for this, or do I need to use a separate third-party parser? Is there an example of how to use facil.io with a multipart form including input fields and file upload?  Thank you.

**Comment by rajesh-krishnan** [comment]
Found a solution using https://github.com/iafonov/multipart-parser-c

**Comment by boazsegev** [comment]
Hi @rajesh-krishnan ,

Thank you for opening this issue.

Depending on which version of facil.io you might be using, you might be interested to read the [HTTP data parsing documentation at facil.io](http://facil.io/0.7.x/http#deeper-http-data-parsing).

Besides functions such as [`http_parse_query`](http://facil.io/0.7.x/http#http_parse_query) and [`http_parse_body`](http://facil.io/0.7.x/http#http_parse_body) you might consider using an external multipart form parser if it better fit your app.

For example, this HTTP response callback will print out the parsed data in JSON format to the terminal:

```c
static void on_http_request(http_s *h) {
  http_parse_query(h);
  http_parse_body(h);
  FIOBJ json = fiobj_obj2json(h->params, 1);
  fprintf(stderr, "%s\n", fiobj_obj2cstr(json).data);
  /* set a response and send it (finnish vs. destroy). */
  http_send_body(h, "Hello World!", 12);
}
```

Pease note that uploaded files will create a "sub-group" / FIOBJ Hash with the following keys:

- `data` - a FIOBJ String with the content of the file.
- `type` - a FIOBJ String with the mime type of the file as provided by the client.
- `filename` - a FIOBJ String with the original filename as provided by the client.

Good Luck!
   Bo.

**Comment by rajesh-krishnan** [comment]
Thank you. That worked splendidly; I have no need for an external parser.

**Comment by boazsegev** [comment]
Cool 😎 

I'm happy to have helped :)
